---
- hosts: haproxy_apache
  remote_user: root
  tasks:
    - name: Install haproxy
      dnf:
        name: haproxy
        state: latest
    - name: add_ports to firewall
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      when: ansible_distribution == 'CentOS'
      loop: 
        - 80/tcp
        - 9000/tcp
      notify: reload firewall
    - name: Configure SELinux
      command: setsebool -P haproxy_connect_any=1
    - name: Add HAProxy cfg
      template:
       src: /etc/ansible/templates/haproxy_apache.j2
       dest: /etc/haproxy/haproxy.cfg
      notify: Start HAProxy
  handlers: 
      - name: reload service firewalld
        systemd:
          name: firewalld
          state: reloaded
      - name: Start haproxy
        systemd:
          name: haproxy
          state: enabled
